# Generated by Django 5.2.8 on 2025-11-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_featured',
        ),
    ]
